# game settings
RES = WIDTH, HEIGHT = 1435, 835
FPS = 60
SCROLL_SPEED = 8
GRAVITY = 0.15

# bird settings
BIRD_POS = WIDTH // 4, HEIGHT // 3
BIRD_SCALE = 0.3
BIRD_ANIMATION_TIME = 300
BIRD_JUMP_VALUE = -6
BIRD_JUMP_ANGLE = 25 # degree bird turns

#ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# pipe settings
PIPE_WIDTH = 250
PIPE_HEIGHT = HEIGHT
DIST_BETWEEN_PIPES = 650
GAP_HEIGHT = 300
HALF_GAP_HEIGHT = GAP_HEIGHT // 2
